### ISSUE TITLE
Please provide example code.

### ISSUE THREAD

**Issue by WizzerWorks** [timtadh/data-structures#9]
Your readme states that you provide "generic types to allow the user to swap out various data structures transparently. The interfaces provide operation for adding, removing, retrieving objects from collections as well as iterating over the collection using functional iterators."

How does this work? For example:

var myKey int16 = 1
table := NewHashTable(10)
var key types.Int16
// XXX: key = myKey
var value interface{} = myData
var err error
value, err = table.Put(key, value)

I don't understand how to assign myKey to the types.Int16 key.

Thank you.

**Comment by timtadh** [comment]
```
k := types.Int16(1)
k2 := int16(12)
k3 := types.Int16(k2)
```
